name: Generate Datas

on:
  schedule: # executar a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Animacao da Cobrinha
      - name: Configurar animacao da Cobrinha
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: anderson20021001
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publicar animacao da Cobrinha
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
